package de.hsrm.mi.swt.SPAsS.presentation.views;

public enum Scenes {
	MAIN_VIEW_CONTROLLER, START_VIEW_CONTROLLER, UPLOAD_VIEW_CONTROLLER, MODULE_INFORMATION_VIEW, SETTINGS_VIEW, SELECT_VIEW, EXAM_VIEW;
}
